### PR TITLE
🍪 👋  cookie.OKTA_USERNAME

### PR DESCRIPTION
**Pull request by chr0n1x**
## Description

Add some supporting code to fetch values from cookies. Just for `OKTA_USERNAME` for the time being.

## Related Issue

N/A

## Motivation and Context

Required for some edu work on my local.

## How Has This Been Tested?

Locally.

## Screenshots (if appropriate):

N/A

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by macdonst** [comment]
@chr0n1x looks good so far.

**Review by macdonst — APPROVED** [review]
@chr0n1x yup, I think this looks good. It's still in draft form, do you want it merged?

**Comment by chr0n1x** [comment]
@macdonst I actually don't mind getting this merged, so thanks! I was keeping it in draft though because I was not sure if it was a valid setup relative to how local setups work, or would work.

**Comment by macdonst** [comment]
@chr0n1x it's a pretty low risk PR since it doesn't even call the cookie code.

**Pull request merged**
